/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register a buyer or organizer (auto-login)
     * @description Creates the user and returns a fresh token pair. The refresh token is registered for rotation/revocation.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: email */
            email: string;
            password: string;
            /** @enum {string} */
            role: 'buyer' | 'organizer';
          };
        };
      };
      responses: {
        /** @description User created with token pair */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Registered'];
          };
        };
        /** @description Role not allowed (admin/guest) */
        403: components['responses']['Error'];
        /** @description Email already taken */
        409: components['responses']['Error'];
        /** @description Validation failed */
        422: components['responses']['Error'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login with email and password
     * @description Rate-limited to 5 requests per minute per IP (Retry-After in 429).
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: email */
            email: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description Token pair */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['TokenPair'];
          };
        };
        /** @description Unknown email or wrong password (indistinguishable) */
        401: components['responses']['Error'];
        /** @description Malformed body */
        422: components['responses']['Error'];
        /** @description Rate limit exceeded */
        429: components['responses']['Error'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Rotate the token pair
     * @description The presented refresh token is revoked and a new pair is issued. Reusing a rotated token returns 401.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            refresh_token: string;
          };
        };
      };
      responses: {
        /** @description New token pair */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['TokenPair'];
          };
        };
        /** @description Invalid */
        401: components['responses']['Error'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Revoke the refresh token
     * @description Idempotent. The access token remains valid until it expires (≤15 min).
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            refresh_token: string;
          };
        };
      };
      responses: {
        /** @description Revoked */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid token */
        401: components['responses']['Error'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Current authenticated identity */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Identity from the access token */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Me'];
          };
        };
        /** @description Missing or invalid token */
        401: components['responses']['Error'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List published events (keyset pagination)
     * @description With mine=true (organizer only) returns ALL events of the caller including drafts and cancelled.
     */
    get: {
      parameters: {
        query?: {
          limit?: number;
          /** @description next_cursor from the previous page */
          cursor?: string;
          /** @description organizer only; requires Bearer token; returns 403 otherwise */
          mine?: 'true';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Page of events */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['EventList'];
          };
        };
        /** @description mine=true requested by a non-organizer */
        403: components['responses']['Error'];
      };
    };
    put?: never;
    /**
     * Create an event with priced ticket categories
     * @description Organizer or admin only. Categories validated (qty ≥ 1, positive price, currency set, https image_url ≤ 500 chars). Tickets generated for every category in the same transaction.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            title: string;
            description?: string;
            /** Format: date-time */
            starts_at: string;
            /** @description optional */
            image_url?: string;
            categories: {
              name: string;
              qty: number;
              price_minor: number;
              /** @example RUB */
              currency: string;
            }[];
          };
        };
      };
      responses: {
        /** @description Event created (draft), tickets generated */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Event'];
          };
        };
        401: components['responses']['Error'];
        /** @description Caller is not an organizer */
        403: components['responses']['Error'];
        422: components['responses']['Error'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/events/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Event details with ticket categories
     * @description Published events are public. Drafts and cancelled are visible only to their owner (or admin); everyone else gets 404.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Event with categories */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Event'];
          };
        };
        /** @description Not found (or not published and not the owner) */
        404: components['responses']['Error'];
        /** @description Bad uuid */
        422: components['responses']['Error'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/events/{id}/publish': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Publish the event (draft → published)
     * @description Owner of the event or admin. FSM rejects repeated publication (409).
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Published */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        401: components['responses']['Error'];
        /** @description Not the owner */
        403: components['responses']['Error'];
        404: components['responses']['Error'];
        /** @description Invalid transition (already published/cancelled) */
        409: components['responses']['Error'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/events/{id}/availability': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Per-category ticket counters
     * @description Cached (10s TTL) + invalidated on release/confirm. snake_case.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Counters with server_time */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Availability'];
          };
        };
        404: components['responses']['Error'];
        /** @description Bad uuid */
        422: components['responses']['Error'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/events/{id}/holds': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reserve tickets (atomic hold, 10 min TTL)
     * @description Atomically captures qty available tickets of the category (SELECT … FOR UPDATE SKIP LOCKED). Concurrent reservers get different tickets or 409 sold-out. Rate-limited to 30 req/min per IP (Retry-After).
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description event id (informational; the category defines the event) */
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: uuid */
            category_id: string;
            qty: number;
          };
        };
      };
      responses: {
        /** @description Hold created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Hold'];
          };
        };
        401: components['responses']['Error'];
        /** @description Not enough tickets */
        409: components['responses']['Error'];
        /** @description Hold expired */
        410: components['responses']['Error'];
        /** @description Validation failed (qty bounds */
        422: components['responses']['Error'];
        /** @description Rate limit exceeded */
        429: components['responses']['Error'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/holds/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Hold status (owner only)
     * @description Lets the client check whether a hold is still active after a page refresh. order_id is filled when the hold became a paid/confirmed order.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Hold status */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Hold'];
          };
        };
        401: components['responses']['Error'];
        /** @description Hold belongs to another user */
        403: components['responses']['Error'];
        404: components['responses']['Error'];
      };
    };
    put?: never;
    post?: never;
    /**
     * Release the hold (tickets back to sale)
     * @description Owner only. Idempotent.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Released (or already released) */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        401: components['responses']['Error'];
        /** @description Hold belongs to another user */
        403: components['responses']['Error'];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/orders': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Purchase saga — create the order from a hold and charge
     * @description Requires idempotency_key (uuid): repeated calls with the same key return the same order (200, created=false). On gateway decline — 402 and tickets are released (compensation). On gateway timeout — 424, order stays pending. Rate-limited to 20 req/min per IP.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: uuid */
            hold_id: string;
            /** Format: uuid */
            idempotency_key: string;
          };
        };
      };
      responses: {
        /** @description Idempotent replay — existing order returned */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Order'];
          };
        };
        /** @description Order created and paid */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Order'];
          };
        };
        401: components['responses']['Error'];
        /** @description Payment declined (order failed */
        402: components['responses']['Error'];
        /** @description Hold belongs to another user */
        403: components['responses']['Error'];
        /** @description Hold not found */
        404: components['responses']['Error'];
        /** @description Hold not active */
        409: components['responses']['Error'];
        /** @description Hold expired */
        410: components['responses']['Error'];
        /** @description Bad idempotency key / hold id */
        422: components['responses']['Error'];
        /** @description Gateway timeout — order pending review */
        424: components['responses']['Error'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/orders/mine': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The authenticated user's orders (history)
     * @description Keyset pagination by created_at DESC (newest first). Cursor format "<RFC3339>|<uuid>", comparison strictly older. limit default 20, max 100.
     */
    get: {
      parameters: {
        query?: {
          limit?: number;
          cursor?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Page of orders */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['OrderList'];
          };
        };
        401: components['responses']['Error'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/orders/{id}/pay': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Charge a pending order */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Paid */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Order'];
          };
        };
        401: components['responses']['Error'];
        /** @description Payment declined */
        402: components['responses']['Error'];
        /** @description Not the owner */
        403: components['responses']['Error'];
        404: components['responses']['Error'];
        /** @description Order is not payable (wrong status) */
        409: components['responses']['Error'];
        /** @description Gateway timeout */
        424: components['responses']['Error'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/orders/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Order status (owner only) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description The order */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Order'];
          };
        };
        401: components['responses']['Error'];
        /** @description Not the owner */
        403: components['responses']['Error'];
        404: components['responses']['Error'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ws/events/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * WebSocket availability stream for the event
     * @description Upgrade to WebSocket. Contract: on EVERY connect (including reconnect) the server immediately sends one full availability snapshot frame, then a new full snapshot on every inventory change. Frame: {"type":"availability","event_id":…,"server_time":…, "categories":[…]} with snake_case fields. Server sends a protocol-level ping every 20 s; automatic browser pongs count as liveness. No client heartbeat required. Allowed origins: configured via WS_ALLOWED_ORIGINS (dev default includes localhost:3000/3005/8080; prod will list the real domain).
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Switching Protocols (WebSocket) */
        101: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not a WebSocket upgrade request */
        501: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/livez': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness probe */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/metrics': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Prometheus exposition */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Plain-text metrics */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': unknown;
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Error: {
      /** @example domain: no tickets available */
      error: string;
    };
    TokenPair: {
      /** @description JWT */
      access?: string;
      /** @description JWT */
      refresh?: string;
    };
    /** @description User created + immediate token pair (auto-login) */
    Registered: {
      /** Format: uuid */
      id?: string;
      /** Format: email */
      email?: string;
      /** @enum {string} */
      role?: 'buyer' | 'organizer';
      access?: string;
      refresh?: string;
    };
    Me: {
      /** Format: uuid */
      id?: string;
      /** @example buyer */
      role?: string;
    };
    Money: {
      /** @description minor units (kopecks) */
      amount?: number;
      /** @example RUB */
      currency?: string;
    };
    TicketCategory: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      event_id?: string;
      name?: string;
      price?: components['schemas']['Money'];
      total_qty?: number;
    };
    Event: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      organizer_id?: string;
      title?: string;
      description?: string;
      /** @description empty if not set */
      image_url?: string;
      /** Format: date-time */
      starts_at?: string;
      /** @enum {string} */
      status?: 'draft' | 'published' | 'cancelled';
      categories?: components['schemas']['TicketCategory'][];
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    EventList: {
      events?: components['schemas']['Event'][];
      /** @description keyset cursor "<RFC3339>|<uuid>"; empty = no more pages */
      next_cursor?: string;
    };
    AvailabilityCategory: {
      /** Format: uuid */
      category_id?: string;
      name?: string;
      price?: components['schemas']['Money'];
      total_qty?: number;
      available?: number;
      held?: number;
      sold?: number;
    };
    Availability: {
      /** Format: uuid */
      event_id?: string;
      /** Format: date-time */
      server_time?: string;
      categories?: components['schemas']['AvailabilityCategory'][];
    };
    Hold: {
      /** Format: uuid */
      hold_id?: string;
      /** @enum {string} */
      status?: 'active' | 'confirmed' | 'released' | 'expired';
      /**
       * Format: date-time
       * @description original hold deadline (creation time + TTL); not rewritten by the lifecycle
       */
      expires_at?: string;
      /** @description number of captured tickets */
      tickets?: number;
      /** Format: date-time */
      server_time?: string;
      /**
       * Format: uuid
       * @description present when the hold became a paid/confirmed order
       */
      order_id?: string;
    };
    Order: {
      /** Format: uuid */
      id?: string;
      /** @enum {string} */
      status?: 'pending' | 'paid' | 'failed' | 'expired' | 'confirmed' | 'refunded';
      total_minor?: number;
      currency?: string;
      /** Format: uuid */
      hold_id?: string;
      /** Format: date-time */
      created_at?: string;
      /** @description present only in POST /orders responses; false = idempotent replay */
      created?: boolean;
    };
    OrderList: {
      orders?: components['schemas']['Order'][];
      /** @description keyset cursor; empty = no more pages */
      next_cursor?: string;
    };
  };
  responses: {
    /** @description Domain error in the uniform envelope */
    Error: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
